require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BeerstylesController do

  # This should return the minimal set of attributes required to create a valid
  # Beerstyle. As you add validations to Beerstyle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BeerstylesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all beerstyles as @beerstyles" do
      beerstyle = Beerstyle.create! valid_attributes
      get :index, {}, valid_session
      assigns(:beerstyles).should eq([beerstyle])
    end
  end

  describe "GET show" do
    it "assigns the requested beerstyle as @beerstyle" do
      beerstyle = Beerstyle.create! valid_attributes
      get :show, {:id => beerstyle.to_param}, valid_session
      assigns(:beerstyle).should eq(beerstyle)
    end
  end

  describe "GET new" do
    it "assigns a new beerstyle as @beerstyle" do
      get :new, {}, valid_session
      assigns(:beerstyle).should be_a_new(Beerstyle)
    end
  end

  describe "GET edit" do
    it "assigns the requested beerstyle as @beerstyle" do
      beerstyle = Beerstyle.create! valid_attributes
      get :edit, {:id => beerstyle.to_param}, valid_session
      assigns(:beerstyle).should eq(beerstyle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Beerstyle" do
        expect {
          post :create, {:beerstyle => valid_attributes}, valid_session
        }.to change(Beerstyle, :count).by(1)
      end

      it "assigns a newly created beerstyle as @beerstyle" do
        post :create, {:beerstyle => valid_attributes}, valid_session
        assigns(:beerstyle).should be_a(Beerstyle)
        assigns(:beerstyle).should be_persisted
      end

      it "redirects to the created beerstyle" do
        post :create, {:beerstyle => valid_attributes}, valid_session
        response.should redirect_to(Beerstyle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved beerstyle as @beerstyle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Beerstyle.any_instance.stub(:save).and_return(false)
        post :create, {:beerstyle => { "name" => "invalid value" }}, valid_session
        assigns(:beerstyle).should be_a_new(Beerstyle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Beerstyle.any_instance.stub(:save).and_return(false)
        post :create, {:beerstyle => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested beerstyle" do
        beerstyle = Beerstyle.create! valid_attributes
        # Assuming there are no other beerstyles in the database, this
        # specifies that the Beerstyle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Beerstyle.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => beerstyle.to_param, :beerstyle => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested beerstyle as @beerstyle" do
        beerstyle = Beerstyle.create! valid_attributes
        put :update, {:id => beerstyle.to_param, :beerstyle => valid_attributes}, valid_session
        assigns(:beerstyle).should eq(beerstyle)
      end

      it "redirects to the beerstyle" do
        beerstyle = Beerstyle.create! valid_attributes
        put :update, {:id => beerstyle.to_param, :beerstyle => valid_attributes}, valid_session
        response.should redirect_to(beerstyle)
      end
    end

    describe "with invalid params" do
      it "assigns the beerstyle as @beerstyle" do
        beerstyle = Beerstyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Beerstyle.any_instance.stub(:save).and_return(false)
        put :update, {:id => beerstyle.to_param, :beerstyle => { "name" => "invalid value" }}, valid_session
        assigns(:beerstyle).should eq(beerstyle)
      end

      it "re-renders the 'edit' template" do
        beerstyle = Beerstyle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Beerstyle.any_instance.stub(:save).and_return(false)
        put :update, {:id => beerstyle.to_param, :beerstyle => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested beerstyle" do
      beerstyle = Beerstyle.create! valid_attributes
      expect {
        delete :destroy, {:id => beerstyle.to_param}, valid_session
      }.to change(Beerstyle, :count).by(-1)
    end

    it "redirects to the beerstyles list" do
      beerstyle = Beerstyle.create! valid_attributes
      delete :destroy, {:id => beerstyle.to_param}, valid_session
      response.should redirect_to(beerstyles_url)
    end
  end

end
