require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CervejariasController do

  # This should return the minimal set of attributes required to create a valid
  # Cervejaria. As you add validations to Cervejaria, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "nome" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CervejariasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cervejarias as @cervejarias" do
      cervejaria = Cervejaria.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cervejarias).should eq([cervejaria])
    end
  end

  describe "GET show" do
    it "assigns the requested cervejaria as @cervejaria" do
      cervejaria = Cervejaria.create! valid_attributes
      get :show, {:id => cervejaria.to_param}, valid_session
      assigns(:cervejaria).should eq(cervejaria)
    end
  end

  describe "GET new" do
    it "assigns a new cervejaria as @cervejaria" do
      get :new, {}, valid_session
      assigns(:cervejaria).should be_a_new(Cervejaria)
    end
  end

  describe "GET edit" do
    it "assigns the requested cervejaria as @cervejaria" do
      cervejaria = Cervejaria.create! valid_attributes
      get :edit, {:id => cervejaria.to_param}, valid_session
      assigns(:cervejaria).should eq(cervejaria)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cervejaria" do
        expect {
          post :create, {:cervejaria => valid_attributes}, valid_session
        }.to change(Cervejaria, :count).by(1)
      end

      it "assigns a newly created cervejaria as @cervejaria" do
        post :create, {:cervejaria => valid_attributes}, valid_session
        assigns(:cervejaria).should be_a(Cervejaria)
        assigns(:cervejaria).should be_persisted
      end

      it "redirects to the created cervejaria" do
        post :create, {:cervejaria => valid_attributes}, valid_session
        response.should redirect_to(Cervejaria.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cervejaria as @cervejaria" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cervejaria.any_instance.stub(:save).and_return(false)
        post :create, {:cervejaria => { "nome" => "invalid value" }}, valid_session
        assigns(:cervejaria).should be_a_new(Cervejaria)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cervejaria.any_instance.stub(:save).and_return(false)
        post :create, {:cervejaria => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cervejaria" do
        cervejaria = Cervejaria.create! valid_attributes
        # Assuming there are no other cervejarias in the database, this
        # specifies that the Cervejaria created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cervejaria.any_instance.should_receive(:update_attributes).with({ "nome" => "MyString" })
        put :update, {:id => cervejaria.to_param, :cervejaria => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested cervejaria as @cervejaria" do
        cervejaria = Cervejaria.create! valid_attributes
        put :update, {:id => cervejaria.to_param, :cervejaria => valid_attributes}, valid_session
        assigns(:cervejaria).should eq(cervejaria)
      end

      it "redirects to the cervejaria" do
        cervejaria = Cervejaria.create! valid_attributes
        put :update, {:id => cervejaria.to_param, :cervejaria => valid_attributes}, valid_session
        response.should redirect_to(cervejaria)
      end
    end

    describe "with invalid params" do
      it "assigns the cervejaria as @cervejaria" do
        cervejaria = Cervejaria.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cervejaria.any_instance.stub(:save).and_return(false)
        put :update, {:id => cervejaria.to_param, :cervejaria => { "nome" => "invalid value" }}, valid_session
        assigns(:cervejaria).should eq(cervejaria)
      end

      it "re-renders the 'edit' template" do
        cervejaria = Cervejaria.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cervejaria.any_instance.stub(:save).and_return(false)
        put :update, {:id => cervejaria.to_param, :cervejaria => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cervejaria" do
      cervejaria = Cervejaria.create! valid_attributes
      expect {
        delete :destroy, {:id => cervejaria.to_param}, valid_session
      }.to change(Cervejaria, :count).by(-1)
    end

    it "redirects to the cervejarias list" do
      cervejaria = Cervejaria.create! valid_attributes
      delete :destroy, {:id => cervejaria.to_param}, valid_session
      response.should redirect_to(cervejarias_url)
    end
  end

end
